sshd_hardening_drop_in_path: /etc/ssh/sshd_config.d/90-hardening.conf

sshd_hardening_options:
  PermitRootLogin: "no"
  PasswordAuthentication: "no"
  KbdInteractiveAuthentication: "no"
  PubkeyAuthentication: "yes"
  PermitEmptyPasswords: "no"
  X11Forwarding: "no"
  AllowAgentForwarding: "no"
  MaxAuthTries: "3"
  LoginGraceTime: "30"
  ClientAliveInterval: "300"
  ClientAliveCountMax: "2"