desktop_wallpapers_enabled: true

desktop_wallpapers_directory: "{{ desktop_wallpapers_home }}/Pictures/Wallpapers"
desktop_wallpapers_home: "{{ ansible_facts.getent_passwd[desktop_user][4] }}"

desktop_wallpapers_manage_user_linger: true
desktop_wallpapers_start_user_manager: true
desktop_wallpapers_start_timers: true
desktop_wallpapers_config_directory_mode: '0700'
desktop_wallpapers_wallpaper_directory_mode: '0750'
desktop_wallpapers_unit_file_mode: '0644'

desktop_wallpapers_hydrapaper_service_name: hydrapaper-wallpaper.service
desktop_wallpapers_hydrapaper_timer_name: hydrapaper-wallpaper.timer
desktop_wallpapers_hydrapaper_on_boot: 2m
desktop_wallpapers_hydrapaper_on_unit_active: 1m