- name: Creates a new user
  ansible.builtin.user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    system: "{{ system | default(false) }}"
    groups: "{{ group | default(omit) }}"
    append: true
    create_home: "{{ create_home | default(true) }}"


- name: configures sudo policy for the user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ user_name }}"
    content: "{{ sudo_policy }}"
    owner: root
    group: root
    mode: '0440'