desktop_packages_default_packages:
  - code
  - steam
  - zsh
  - snapd
  - qdmr
  - chezmoi
  - rclone

desktop_packages_extra_packages: []
desktop_packages_excluded_packages: []

desktop_packages_default_groups:
  - "@virtualization"

desktop_packages_extra_groups: []
desktop_packages_excluded_groups: []

desktop_packages_state: present
desktop_packages_update_cache: true

desktop_packages_manage_snapd: true
desktop_packages_snapd_services:
  - snapd.socket
desktop_packages_create_classic_snap_link: true
desktop_packages_classic_snap_link_path: /snap
desktop_packages_classic_snap_target: /var/lib/snapd/snap

desktop_packages_manage_virtualization: true
desktop_packages_manage_virtualization_user: true
desktop_user: ""
desktop_packages_libvirt_services:
  - libvirtd
desktop_packages_libvirt_groups:
  - libvirt