tailscale_state: present
tailscale_release_stability: stable
tailscale_hostname: "{{ host_name | default(inventory_hostname) }}"
tailscale_accept_routes: false
tailscale_advertise_exit_node: false
tailscale_advertise_routes: []
tailscale_tags: []
tailscale_ssh: false
tailscale_extra_args: []
tailscale_up_timeout: "120"
tailscale_oauth_ephemeral: true
tailscale_oauth_preauthorized: false
tailscale_verbose: false
tailscale_insecurely_log_authkey: false
tailscale_auth_key_in_state: true
tailscale_manage_binaries_skip: false