- name: Install and configure OpenSSH Server
  ansible.builtin.dnf5:
    name: openssh-server
    state: present
    update_cache: yes

- name: Start & Enable SSH Service
  ansible.builtin.systemd:
    name: sshd
    state: started
    enabled: yes

- name: Import sshd_config template
  ansible.builtin.get_url:
    url: https://githubusercontent.com
    dest: /home/user/target_directory/file.txt
    mode: '0644'
    # Optional: If you need to force re-download even if it exists
    # force: yes
