- hosts: localhost
  become: true
  vars:
    desktop_wallpapers_enabled: true
  vars_prompt:
    - name: desktop_user
      prompt: "Enter the local desktop user we are configuring"
      private: no

  roles:
    - role: desktop_repos
    - role: desktop_packages
    - role: desktop_flatpacks
    - role: desktop_wallpapers
